version: '3.8'

services:
  redis:
    image: 'redis:latest'
    container_name: 'redis'
    ports:
      - '6379:6379'

  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'pokemon2pro'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: 'nestjs_app'
    ports:
      - '3000:3000'
    environment:
      POSTGRESS_HOST: postgres
      POSTGRESS_PORT: 5432
      POSTGRESS_USERNAME: admin
      POSTGRESS_PASSWORD: admin
      POSTGRESS_DATABASE: pokemon2pro
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod

volumes:
  postgres_data:
